
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Font;
import java.awt.Panel;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import java.awt.print.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import javax.swing.table.TableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.helpers.XSSFRowShifter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsimran singh
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    
    int cash;
    database db=new database();
    JTable forprint;
    
    FileOutputStream fos;
    ResultSet forexcel;
    int flag=0;
    String event;
    public Admin() {
        initComponents();
         Toolkit tk = Toolkit.getDefaultToolkit();
      int xsize= (int) tk.getScreenSize().getWidth();
      int ysize= (int) tk.getScreenSize().getHeight();
      
      this.setSize(xsize, ysize);
      
      p1.setBackground(Color.BLACK);
      p1.setOpaque(true);
      
      Font f= new Font(null, Font.PLAIN, 18);

         t1.setFont(f);
         t2.setFont(f);
         l1.removeAllItems();
         l1.addItem("BOOKNO");
         l1.addItem("EVENT");
         l1.addItem("NAME");
         l1.addItem("REGISTRATIONNO");
         l1.addItem("ACCOMODATION");
         l1.addItem("COLLEGE");
         
         t2.setEditable(false);
         
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l1 = new javax.swing.JComboBox();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        b4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsimran singh\\Desktop\\loader_logo.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN PAGE");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(456, 456, 456)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("SEARCH BY");

        l1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("GENERATE CASH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        b4.setText("COLLEGE COUNT");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        jButton5.setText("EXPORT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b4)
                .addGap(58, 58, 58)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(885, 885, 885))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(684, Short.MAX_VALUE))
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close-button-png-30.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton3)
                .addGap(67, 67, 67)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 190, Short.MAX_VALUE))
            .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            
            
        String data[][]; 
        String cashqry;
        
        String value=(String) l1.getSelectedItem();
        String qry;
        
        
        String va = null;
        
        if(value.equals("ACCOMODATION"))
        {
            
             String tofind=t1.getText();
            qry="select * from register where ACCOMODATION ='"+tofind+"' order by REGISTRATIONNO";
            flag=5;
            cashqry="select sum(amount) from register where ACCOMODATION ='"+tofind+"' order by REGISTRATIONNO";
            
            
        }
        else if(value.equals("EVENT"))
        {
         String tofind=t1.getText();
            qry="select * from register where "+tofind+"='"+tofind+"' order by REGISTRATIONNO";
            flag=1;
            va=tofind;
            cashqry="select sum(amount) from register where "+tofind+"='"+tofind+"'";
        }
        
        else if(value.equals("COLLEGE"))
        {
         String tofind=t1.getText();
            qry="select * from register where COLLEGE='"+tofind+"' order by REGISTRATIONNO";
            flag=2;
            va="COLLEGE";
            cashqry="select sum(amount) from register where COLLEGE='"+tofind+"'";
        }
        
        
        
        else
        {
            if(value.equals("NAME"))
            {
                String tofind=t1.getText();
                 qry="select * from register where "+ value+"='"+tofind+"' order by REGISTRATIONNO";
                 flag=2;
                 cashqry="select sum(amount) from register where "+ value+"='"+tofind+"'";
            }
            
            else
            {
                int tofind=Integer.parseInt(t1.getText());
                 qry="select * from register where "+ value+" = "+tofind+" order by REGISTRATIONNO";
                 flag=3;
                 cashqry="select sum(amount) from register where "+ value+" = "+tofind+" order by REGISTRATIONNO";
            }
            
           
        }
        
        
       ResultSet cashrs=db.execute(cashqry);
       cashrs.next();
       cash=cashrs.getInt("sum(amount)");
       
        ResultSet rs=db.execute(qry);
        
        rs.last();
        
        int n=rs.getRow();
        rs.beforeFirst();
           
            
            if(flag==5)//FOR ACCOMODATION
            {
                data= new String[n][10];
                String cols[]={"SR","BOOK NO","REGISTRATION NO","NAME","FATHERS NAME","PHONE NO","COLLEGE","COLLEGE ID","AMOUNT","ACCOMODATION"};
                 int i=0;
            int j=0;
            int count=1;
            while(rs.next())
            {
                data[i][j]=Integer.toString(count);
                 data[i][++j]=rs.getString("BOOKNO");
               data[i][++j]=rs.getString("REGISTRATIONNO");
               data[i][++j]=rs.getString("NAME");
               data[i][++j]=rs.getString("FNAME");
               data[i][++j]=rs.getString("PHONENO");
               data[i][++j]=rs.getString("COLLEGE");
               data[i][++j]=rs.getString("COLLEGEID");
               
               data[i][++j]=rs.getString("AMOUNT");
               
               data[i][++j]=rs.getString("ACCOMODATION");
               
                j=0;
                i++;
                count++;
               
            }
               
              JTable jt = new JTable(data,cols);
           
                jt.setFont(new Font("TimesNewRoman",Font.PLAIN,16));
                jt.setRowHeight(30);
              JScrollPane jsp = new JScrollPane(jt);
              
              view v= new view();
              v.setVisible(true);
              v.sho(jsp);
              
              forprint=jt;
              
              rs.beforeFirst();
              forexcel=rs; 
            }
            
            if(flag==1) // for single event
            {
                data= new String[n][10];
                String cols[]={"SR","BOOK NO","REGISTRATION NO","NAME","FATHERS NAME","PHONE NO","COLLEGE","COLLEGE ID","AMOUNT","EVENT"};
                 int i=0;
            int j=0;
            int count=1;
            while(rs.next())
            {
                 data[i][j]=Integer.toString(count);
                 data[i][++j]=rs.getString("BOOKNO");
               data[i][++j]=rs.getString("REGISTRATIONNO");
               data[i][++j]=rs.getString("NAME");
               data[i][++j]=rs.getString("FNAME");
               data[i][++j]=rs.getString("PHONENO");
               data[i][++j]=rs.getString("COLLEGE");
               data[i][++j]=rs.getString("COLLEGEID");
               
               data[i][++j]=rs.getString("AMOUNT");
               
               data[i][++j]=rs.getString(va);
               
                j=0;
                i++;
                count++;
               
            }
               
              JTable jt = new JTable(data,cols);
               
                jt.setFont(new Font("TimesNewRoman",Font.PLAIN,16));
                  jt.setRowHeight(30);
              JScrollPane jsp = new JScrollPane(jt);
              
              view v= new view();
              v.setVisible(true);
              v.sho(jsp);
               
            forprint=jt;
            rs.beforeFirst();
              forexcel=rs; 
              event=va;
                
            }
            
        if(flag==2 || flag==3) // for book no,college,name,registration no
        {
            data=new String[n][11];
            String cols[]={"SR","BOOK NO","REGISTRATION NO","NAME","FATHERS NAME","PHONE NO","COLLEGE","COLLEGE ID","ACCOMODATION","AMOUNT","EVENTS"};
                 int i=0;
            int j=0;
            int count=1;
            while(rs.next())
            {
                 data[i][j]=Integer.toString(count);
                 data[i][++j]=rs.getString("BOOKNO");
               data[i][++j]=rs.getString("REGISTRATIONNO");
               data[i][++j]=rs.getString("NAME");
               data[i][++j]=rs.getString("FNAME");
               data[i][++j]=rs.getString("PHONENO");
               data[i][++j]=rs.getString("COLLEGE");
               data[i][++j]=rs.getString("COLLEGEID");
               data[i][++j]=rs.getString("ACCOMODATION");
               data[i][++j]=rs.getString("AMOUNT");
               String toput=rs.getString("VOGUE")+" "+rs.getString("STOMPTHEYARD")+" "+rs.getString("FANTASTICTOE")+" "+rs.getString("MATINEE")+" "+rs.getString("HALLABOL")+" "+rs.getString("PAINTBALL")+" "+rs.getString("ZORBING")+" "+rs.getString("EFUSION")+" "+rs.getString("SUMOFIGHTING")+" "+rs.getString("VRFILMING")+" "+rs.getString("MRANDMRSALGO")+" "+rs.getString("COUNTERSTRIKE")+" "+rs.getString("FIFA")+" "+rs.getString("3ON3BASKETBALL")+" "+rs.getString("MOSTWANTED")+" "+rs.getString("MINIMILITIA")+" "+rs.getString("8BALLOFFIRE")+" "+rs.getString("4ASIDESOCCER")+" "+rs.getString("SNAPTEXT");
               data[i][++j]=toput;
               
               
               

                j=0;
                i++;
                count++;
            }
          JTable jt =new JTable(data,cols);
           
              jt.setFont(new Font("TimesNewRoman",Font.PLAIN,16));
                jt.setRowHeight(30);
               
          JScrollPane jsp= new JScrollPane(jt);
         
          
          view v= new view();
          v.setVisible(true);
          
          
          v.sho(jsp);
          
          
          forprint=jt;
            rs.beforeFirst();
              forexcel=rs;
             
        }
        
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
             String se=Integer.toString(cash);
        
        t2.setText(se);
        t2.setEditable(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            MessageFormat header= new MessageFormat("TO PRINT");
            
            MessageFormat footer= new MessageFormat("PAGE");
            
            forprint.print(JTable.PrintMode.NORMAL, header, footer);
            
            
            
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        
         String data[][];
        
        String qry=" select count(COLLEGE) as count,COLLEGE from register group by COLLEGE";
        
        String cols[]={"COLLEGE","NO OF ENTRIES"};
        try {
            ResultSet rs=db.execute(qry);
            
            rs.last();
           int n= rs.getRow();
           rs.beforeFirst();
           data= new String[n][2];
           int i=0;
           int j=0;
           while(rs.next())
           {
               data[i][j]=rs.getString("COLLEGE");
               data[i][++j]=rs.getString("count");
               
               j=0;
               i++;
               
           }
            JTable jt =new JTable(data,cols);
           
              jt.setFont(new Font("TimesNewRoman",Font.PLAIN,16));
                jt.setRowHeight(30);
               
          JScrollPane jsp= new JScrollPane(jt);
         
          
          view v= new view();
          v.setVisible(true);
          
          
          v.sho(jsp);
          
          
          forprint=jt;
          
          rs.beforeFirst();
         XSSFWorkbook workbook = new XSSFWorkbook(); 
      XSSFSheet spreadsheet = workbook
      .createSheet("COLLEGE COUNT");
      XSSFRow row=spreadsheet.createRow(1);
      XSSFCell cell;
      cell=row.createCell(1);
      cell.setCellValue("COLLEGE");
      cell=row.createCell(2);
      cell.setCellValue("COUNT");
    
      int k=2;
      while(rs.next())
      {
         row=spreadsheet.createRow(k);
         cell=row.createCell(1);
         cell.setCellValue(rs.getString("COLLEGE"));
         cell=row.createCell(2);
         cell.setCellValue(rs.getInt("COUNT"));
 
         k++;
      }
      FileOutputStream out = new FileOutputStream(
      new File("G:\\ALGORYTHM 2K17\\collegecount.xlsx"));
      workbook.write(out);
      out.close(); 
           
      JOptionPane.showMessageDialog(null, "COLLEGE HAS BEEN GENERATED");
            
            
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_b4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
       db.connectionclosing();
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try
        {
            
        
        XSSFWorkbook wb= new XSSFWorkbook();
        
        if(flag==5)
        {
            XSSFSheet spreadsheet= wb.createSheet("ACCOMODATION");
            
            XSSFRow row= spreadsheet.createRow(1);
            
            
            XSSFCell cell;
            cell=row.createCell(1);
            cell.setCellValue("Sr");
            cell=row.createCell(2);
            cell.setCellValue("Book N0");
            cell=row.createCell(3);
            cell.setCellValue("Registration No");
            cell=row.createCell(4);
            cell.setCellValue("Name");
            cell=row.createCell(5);
            cell.setCellValue("F.Name");
            cell=row.createCell(6);
            cell.setCellValue("Phone");
            cell=row.createCell(7);
            cell.setCellValue("College");
            cell=row.createCell(8);
            cell.setCellValue("College ID");
            cell=row.createCell(9);
            cell.setCellValue("Accomodation");
            
            int k=2;
            int counter=1;
            while(forexcel.next())
            {
                row=spreadsheet.createRow(k);
                cell=row.createCell(1);
                cell.setCellValue(Integer.toString(counter));
                cell=row.createCell(2);
                cell.setCellValue(forexcel.getString("BOOKNO"));
                cell=row.createCell(3);
                cell.setCellValue(forexcel.getString("REGISTRATIONNO"));
                cell=row.createCell(4);
                cell.setCellValue(forexcel.getString("NAME"));
                 cell=row.createCell(5);
                cell.setCellValue(forexcel.getString("FNAME")); 
                 cell=row.createCell(6);
                cell.setCellValue(forexcel.getString("PHONENO"));
                cell=row.createCell(7);
                cell.setCellValue(forexcel.getString("COLLEGE"));
                cell=row.createCell(8);
                cell.setCellValue(forexcel.getString("COLLEGEID"));
                cell=row.createCell(9);
                cell.setCellValue(forexcel.getString("ACCOMODATION"));
                
 
         k++;
         counter++;
                
                
            }
            
            
             
            
            
            
        }
        
        
        if(flag==1)
        {
            
              XSSFSheet spreadsheet= wb.createSheet((t1.getText()));
            
            XSSFRow row= spreadsheet.createRow(1);
            
            
            XSSFCell cell;
            cell=row.createCell(1);
            cell.setCellValue("Sr");
            cell=row.createCell(2);
            cell.setCellValue("Book N0");
            cell=row.createCell(3);
            cell.setCellValue("Registration No");
            cell=row.createCell(4);
            cell.setCellValue("Name");
            cell=row.createCell(5);
            cell.setCellValue("F.Name");
            cell=row.createCell(6);
            cell.setCellValue("Phone");
            cell=row.createCell(7);
            cell.setCellValue("College");
            cell=row.createCell(8);
            cell.setCellValue("College ID");
            cell=row.createCell(9);
            cell.setCellValue("Accomodation");
            cell=row.createCell(10);
            cell.setCellValue("Amount");
            cell=row.createCell(11);
            cell.setCellValue("Event");

            
            int k=2;
            int counter=1;
            while(forexcel.next())
            {
                row=spreadsheet.createRow(k);
                cell=row.createCell(1);
                cell.setCellValue(Integer.toString(counter));
                cell=row.createCell(2);
                cell.setCellValue(forexcel.getString("BOOKNO"));
                cell=row.createCell(3);
                cell.setCellValue(forexcel.getString("REGISTRATIONNO"));
                cell=row.createCell(4);
                cell.setCellValue(forexcel.getString("NAME"));
                cell=row.createCell(5);
                cell.setCellValue(forexcel.getString("FNAME")); 
                cell=row.createCell(6);
                cell.setCellValue(forexcel.getString("PHONENO"));
                cell=row.createCell(7);
                cell.setCellValue(forexcel.getString("COLLEGE"));
                cell=row.createCell(8);
                cell.setCellValue(forexcel.getString("COLLEGEID"));
                cell=row.createCell(9);
                cell.setCellValue(forexcel.getString("ACCOMODATION"));
                cell=row.createCell(10); 
                cell.setCellValue(forexcel.getString("AMOUNT"));
                cell=row.createCell(11); 
                cell.setCellValue(forexcel.getString(event));
                
                
 
               k++;
               counter++;
                
                
            }
        }
        
        
        
        if(flag==2 || flag==3)
        {
             XSSFSheet spreadsheet= wb.createSheet((t1.getText()));
            
            XSSFRow row= spreadsheet.createRow(1);
            
            
            XSSFCell cell;
            cell=row.createCell(1);
            cell.setCellValue("Sr");
            cell=row.createCell(2);
            cell.setCellValue("Book N0");
            cell=row.createCell(3);
            cell.setCellValue("Registration No");
            cell=row.createCell(4);
            cell.setCellValue("Name");
            cell=row.createCell(5);
            cell.setCellValue("F.Name");
            cell=row.createCell(6);
            cell.setCellValue("Phone");
            cell=row.createCell(7);
            cell.setCellValue("College");
            cell=row.createCell(8);
            cell.setCellValue("College ID");
            cell=row.createCell(9);
            cell.setCellValue("Accomodation");
            cell=row.createCell(10);
            cell.setCellValue("Amount");
            cell=row.createCell(11);
            cell.setCellValue("Event");

            
            int k=2;
            int counter=1;
            while(forexcel.next())
            {
                row=spreadsheet.createRow(k);
                cell=row.createCell(1);
                cell.setCellValue(Integer.toString(counter));
                cell=row.createCell(2);
                cell.setCellValue(forexcel.getString("BOOKNO"));
                cell=row.createCell(3);
                cell.setCellValue(forexcel.getString("REGISTRATIONNO"));
                cell=row.createCell(4);
                cell.setCellValue(forexcel.getString("NAME"));
                cell=row.createCell(5);
                cell.setCellValue(forexcel.getString("FNAME")); 
                cell=row.createCell(6);
                cell.setCellValue(forexcel.getString("PHONENO"));
                cell=row.createCell(7);
                cell.setCellValue(forexcel.getString("COLLEGE"));
                cell=row.createCell(8);
                cell.setCellValue(forexcel.getString("COLLEGEID"));
                cell=row.createCell(9);
                cell.setCellValue(forexcel.getString("ACCOMODATION"));
                cell=row.createCell(10); 
                cell.setCellValue(forexcel.getString("AMOUNT"));
                cell=row.createCell(11); 
                 String toput=forexcel.getString("VOGUE")+" "+forexcel.getString("STOMPTHEYARD")+" "+forexcel.getString("FANTASTICTOE")+" "+forexcel.getString("MATINEE")+" "+forexcel.getString("HALLABOL")+" "+forexcel.getString("PAINTBALL")+" "+forexcel.getString("ZORBING")+" "+forexcel.getString("EFUSION")+" "+forexcel.getString("SUMOFIGHTING")+" "+forexcel.getString("VRFILMING")+" "+forexcel.getString("MRANDMRSALGO")+" "+forexcel.getString("COUNTERSTRIKE")+" "+forexcel.getString("FIFA")+" "+forexcel.getString("3ON3BASKETBALL")+" "+forexcel.getString("MOSTWANTED")+" "+forexcel.getString("MINIMILITIA")+" "+forexcel.getString("8BALLOFFIRE")+" "+forexcel.getString("4ASIDESOCCER")+" "+forexcel.getString("SNAPTEXT");
                cell.setCellValue(toput);
                
                
 
               k++;
                counter++;
                
            }
            
            
            
        }
        
        
        String Filename=JOptionPane.showInputDialog("ENTER THE FILE NAME");
        
         fos = new FileOutputStream(
      new File("G:\\ALGORYTHM 2K17\\"+Filename+".xlsx"));
      wb.write(fos);
      fos.close(); 
      
      JOptionPane.showMessageDialog(null, "FILE SUCCESFULLY CONVERTED TO EXCEL");
           
        
        }
        
        
        
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JComboBox l1;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
