
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javafx.scene.text.FontWeight;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsimran singh
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
   database db;
    ButtonGroup bg1;
    
    Set ar;
    
    
    int bookno;
    int rno;
    String name=new String();
    String fname=new String();
     String phoneno;
    String college=new String();
    String collegeid;
    String accomodation=new String();
    int amount;
    String vogue=new String();
    String stomptheyard=new String();
    String fantastictoe=new String();
    String matinee=new String();
    String hallabol=new String();
    String efusion=new String();
    String paintball=new String();
    String sumo=new String();
    String algo=new String();
    String vr=new String();
    String zorbing=new String();
    String fifa=new String();
    String cs=new String();
    String balloffire=new String();
    String soccer=new String();
    String mini=new String();
    String nfs=new String();
    String basketball=new String();
    String snaptext=new String();
     
    public Registration() {
        initComponents();
     /* Toolkit tk = Toolkit.getDefaultToolkit();
      int xsize= (int) tk.getScreenSize().getWidth();
     int ysize= (int) tk.getScreenSize().getHeight();
     */
     
      
    
      p1.setBackground(Color.black);
      p1.setOpaque(true);
      r1.setActionCommand("YES");
      r2.setActionCommand("NO");
       bg1= new ButtonGroup();
      bg1.add(r1);
      bg1.add(r2);
      
      Font f= new Font("NONE", Font.PLAIN, 18);
      
      t1.setFont(f);
      t2.setFont(f);
      t3.setFont(f);
      t4.setFont(f);
      t5.setFont(f);
      t6.setFont(f);
      t7.setFont(f);
      t8.setFont(f);
      
        Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK, true);
        
       db=new database();
       
       ar= new HashSet();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        t8 = new javax.swing.JTextField();
        lc1 = new javax.swing.JCheckBox();
        lc2 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        c4 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        c5 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        c6 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        c7 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        c10 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        c11 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        labell = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        c12 = new javax.swing.JCheckBox();
        c13 = new javax.swing.JCheckBox();
        c14 = new javax.swing.JCheckBox();
        c16 = new javax.swing.JCheckBox();
        c18 = new javax.swing.JCheckBox();
        c15 = new javax.swing.JCheckBox();
        c17 = new javax.swing.JCheckBox();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        c19 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loader_logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRATIONS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN LOGIN");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("VIEW WORK");
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(502, 502, 502)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(158, 158, 158)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel43))
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Booklet No ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 40, 120, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Registration No ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 120, 170, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 210, 90, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Father's Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 300, 160, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Phone no");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 400, 110, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("College");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 500, 110, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("College Id");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 610, 110, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("ACCOMODATION");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 720, 200, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Amount");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 820, 120, 50);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(190, 40, 240, 30);
        jPanel1.add(t2);
        t2.setBounds(190, 120, 240, 30);

        t3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(t3);
        t3.setBounds(190, 210, 240, 30);
        jPanel1.add(t4);
        t4.setBounds(190, 300, 240, 30);
        jPanel1.add(t5);
        t5.setBounds(190, 410, 240, 30);
        jPanel1.add(t6);
        t6.setBounds(190, 500, 240, 30);
        jPanel1.add(t7);
        t7.setBounds(190, 610, 240, 30);

        r1.setText("YES");
        jPanel1.add(r1);
        r1.setBounds(240, 720, 80, 30);

        r2.setText("NO");
        jPanel1.add(r2);
        r2.setBounds(370, 720, 80, 30);
        jPanel1.add(t8);
        t8.setBounds(190, 830, 230, 30);

        lc1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lc1.setText("LOCK");
        lc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lc1ActionPerformed(evt);
            }
        });
        jPanel1.add(lc1);
        lc1.setBounds(460, 40, 65, 25);

        lc2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lc2.setText("LOCK");
        lc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lc2ActionPerformed(evt);
            }
        });
        jPanel1.add(lc2);
        lc2.setBounds(460, 120, 65, 25);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setText("EVENTS");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1160, 20, 140, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("RHYTMRATZ :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1230, 60, 180, 50);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("VOGUE");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(950, 140, 100, 16);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel16.setText("STOMP THE YARD");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1180, 130, 210, 28);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel17.setText("FANTASTIC TOE");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1530, 130, 210, 28);

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(1080, 130, 93, 25);
        jPanel1.add(c2);
        c2.setBounds(1420, 130, 25, 25);
        jPanel1.add(c3);
        c3.setBounds(1760, 130, 25, 25);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel18.setText(" ABHIVYAKTI :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(1210, 210, 190, 28);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel19.setText("MATINEE");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(950, 270, 120, 28);
        jPanel1.add(c4);
        c4.setBounds(1100, 270, 25, 25);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel20.setText("HALLA BOL");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1280, 270, 160, 28);
        jPanel1.add(c5);
        c5.setBounds(1450, 270, 25, 25);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel21.setText(" SYMPHONY :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(1220, 340, 180, 28);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel22.setText("EUPHONIOUS FUSION");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(950, 400, 240, 28);

        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        jPanel1.add(c6);
        c6.setBounds(1210, 400, 25, 25);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel23.setText("FUN FIESTA");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(1230, 450, 150, 28);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel24.setText("PAINT BALL");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(950, 520, 160, 28);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel25.setText("SUMO FIGHTING");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(1200, 520, 200, 28);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel26.setText("MR & MRS ALGO");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(1550, 510, 200, 28);
        jPanel1.add(c7);
        c7.setBounds(1130, 520, 25, 25);
        jPanel1.add(c8);
        c8.setBounds(1450, 520, 25, 25);
        jPanel1.add(c9);
        c9.setBounds(1770, 510, 101, 25);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel27.setText("VR FILMING");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(950, 590, 160, 28);
        jPanel1.add(c10);
        c10.setBounds(1130, 590, 25, 25);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel28.setText("ZORBING");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(1200, 580, 110, 28);
        jPanel1.add(c11);
        c11.setBounds(1450, 580, 25, 25);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel29.setText("GAME WRAP");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(1220, 640, 180, 28);

        label12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label12.setText("COUNTER STRIKE");
        jPanel1.add(label12);
        label12.setBounds(920, 720, 210, 28);

        labell.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labell.setText("4-A SIDE SOCCER");
        jPanel1.add(labell);
        labell.setBounds(920, 770, 193, 28);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel32.setText("MOST WANTED");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(920, 820, 173, 28);

        label13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label13.setText("FIFA");
        jPanel1.add(label13);
        label13.setBounds(1260, 710, 70, 28);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel34.setText("MINI MILITIA");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(1250, 760, 151, 28);

        label14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label14.setText("3 ON 3 BASKET BALL");
        jPanel1.add(label14);
        label14.setBounds(1530, 700, 236, 28);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel36.setText("8 BALL OF FIRE");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(1250, 820, 175, 28);
        jPanel1.add(c12);
        c12.setBounds(1140, 720, 25, 25);
        jPanel1.add(c13);
        c13.setBounds(1460, 710, 25, 25);
        jPanel1.add(c14);
        c14.setBounds(1780, 700, 25, 25);
        jPanel1.add(c16);
        c16.setBounds(1460, 760, 101, 25);
        jPanel1.add(c18);
        c18.setBounds(1460, 820, 25, 25);
        jPanel1.add(c15);
        c15.setBounds(1140, 770, 25, 25);
        jPanel1.add(c17);
        c17.setBounds(1140, 830, 25, 25);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colored_line-t2.jpg"))); // NOI18N
        jLabel37.setText("jLabel37");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(1210, 100, 190, 20);

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsimran singh\\Desktop\\colored_line-t2.jpg")); // NOI18N
        jLabel38.setText("jLabel37");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(1210, 100, 190, 20);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colored_line-t2.jpg"))); // NOI18N
        jLabel39.setText("jLabel39");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(1210, 240, 180, 16);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colored_line-t2.jpg"))); // NOI18N
        jPanel1.add(jLabel40);
        jLabel40.setBounds(1210, 370, 184, 8);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colored_line-t2.jpg"))); // NOI18N
        jPanel1.add(jLabel41);
        jLabel41.setBounds(1210, 480, 184, 8);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colored_line-t2.jpg"))); // NOI18N
        jPanel1.add(jLabel42);
        jLabel42.setBounds(1210, 670, 184, 8);

        b1.setText("SUBMIT");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(1640, 810, 190, 50);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel30.setText("SNAPTEXT");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(1550, 570, 200, 50);
        jPanel1.add(c19);
        c19.setBounds(1770, 580, 40, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void lc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lc2ActionPerformed
        // TODO add your handling code here:
        
        if(lc2.isSelected())
        {
            t2.setEditable(false);
            t6.setEditable(false);
            
        }
        else
            
        {
            
            t2.setEditable(true);
            t6.setEditable(true);
            
            t2.setText("");
            t6.setText("");
            c1.setSelected(false);
            c2.setSelected(false);
            c3.setSelected(false);
            c4.setSelected(false);
            c5.setSelected(false);
            c6.setSelected(false);
            c7.setSelected(false);
            c8.setSelected(false);
            c9.setSelected(false);
            c10.setSelected(false);
            c11.setSelected(false);
            c12.setSelected(false);
            c13.setSelected(false);
            c14.setSelected(false);
            c15.setSelected(false);
            c16.setSelected(false);
            c17.setSelected(false);
            c18.setSelected(false);
            c19.setSelected(false);
             bg1.clearSelection();
     vogue="";
     stomptheyard="";
     fantastictoe="";
     matinee="";
     hallabol="";
     efusion="";
     paintball="";
     sumo="";
     algo="";
     vr="";
     zorbing="";
     fifa="";
     cs="";
     balloffire="";
     soccer="";
     mini="";
     nfs="";
     basketball="";
     snaptext="";
            
            
            
        }
        
    }//GEN-LAST:event_lc2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        AdminLogin a= new AdminLogin();
        a.setVisible(true);
        a.pack();
        
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lc1ActionPerformed
        // TODO add your handling code here:
        if(lc1.isSelected())
        {
            int toadd=Integer.parseInt(t1.getText());
            t1.setEditable(false);
            ar.add(toadd);
        }
        else
        {
            t1.setEditable(true);
        }
        
        
    }//GEN-LAST:event_lc1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            
        
        
        bookno=Integer.parseInt(t1.getText());
        rno=Integer.parseInt(t2.getText());
        name=t3.getText();
        fname=t4.getText();
        phoneno=t5.getText();
        college=t6.getText();
        collegeid=t7.getText();
      accomodation=bg1.getSelection().getActionCommand();
      amount=Integer.parseInt(t8.getText());
      
      if(c1.isSelected())
      {
          vogue ="VOGUE";
      }
      if(c2.isSelected())
      {
         stomptheyard ="STOMPTHEYARD";
      }
       if(c3.isSelected())
      {
          fantastictoe ="FANTASTICTOE";
      }
       if(c4.isSelected())
      {
          matinee ="MATINEE";
      }
       if(c5.isSelected())
      {
          hallabol ="HALLABOL";
      }
       if(c6.isSelected())
      {
          efusion ="EFUSION";
      }
       if(c7.isSelected())
      {
          paintball ="PAINTBALL";
      }
       if(c8.isSelected())
      {
          sumo="SUMOFIGHTING";
      }
       if(c9.isSelected())
      {
          algo ="MRANDMRSALGO";
      }
       if(c10.isSelected())
      {
          vr ="VRFILMING";
      }
       if(c11.isSelected())
      {
          zorbing="ZORBING";
      }
       if(c12.isSelected())
      {
          cs ="COUNTERSTRIKE";
      }
       if(c13.isSelected())
      {
          fifa ="FIFA";
      }
       if(c14.isSelected())
      {
          basketball ="3ON3BASKETBALL";
      }
       if(c15.isSelected())
      {
          soccer ="4ASIDESOCCER";
      }
       if(c16.isSelected())
      {
         mini ="MINIMILITIA";
      }
       if(c17.isSelected())
      {
          nfs ="MOSTWANTED";
      }
       if(c18.isSelected())
      {
          balloffire ="8BALLOFFIRE";
      }
       if(c19.isSelected())
       {
           snaptext="SNAPTEXT";
       }
       
       String str= new String();
       str="insert into register values("+bookno+","+rno+",'"+name+"','"+fname+"','"+phoneno+"','"+college+"','"+collegeid+"','"+accomodation+"',"+amount+",'"+vogue+"','"+stomptheyard+"','"+fantastictoe+"','"+matinee+"','"+hallabol+"','"+efusion+"','"+paintball+"','"+sumo+"','"+algo+"','"+vr+"','"+zorbing+"','"+cs+"','"+fifa+"','"+basketball+"','"+soccer+"','"+mini+"','"+nfs+"','"+balloffire+"','"+snaptext+"')";
       
        db.update(str);
       
        
        
      int flag=0;
        if(lc1.isSelected())
        {
            
        }
        else
        {
            t1.setText("");
        }
        
        if(lc2.isSelected())
        {
            t3.setText("");
            t4.setText("");
            t5.setText("");
            t7.setText("");
            
            t8.setText("");
            flag=1;
        }
        else
        {
             t2.setText("");
              t3.setText("");
               t4.setText("");
                t5.setText("");
                 t6.setText("");
                  t7.setText(""); 
                  t8.setText("");
                  
                  vogue="";
                  stomptheyard="";
     fantastictoe="";
     matinee="";
     hallabol="";
     efusion="";
     paintball="";
     sumo="";
     algo="";
     vr="";
     zorbing="";
     fifa="";
     cs="";
     balloffire="";
     soccer="";
     mini="";
     nfs="";
     basketball="";
     snaptext="";
                  
            
        }
        if(flag!=1)
        {
            c1.setSelected(false);
            c2.setSelected(false);
            c3.setSelected(false);
            c4.setSelected(false);
            c5.setSelected(false);
            c6.setSelected(false);
            c7.setSelected(false);
            c8.setSelected(false);
            c9.setSelected(false);
            c10.setSelected(false);
            c11.setSelected(false);
            c12.setSelected(false);
            c13.setSelected(false);
            c14.setSelected(false);
            c15.setSelected(false);
            c16.setSelected(false);
            c17.setSelected(false);
            c18.setSelected(false);
            c19.setSelected(false);
             bg1.clearSelection();
            
        }
       
        
        JOptionPane.showMessageDialog(null,"THE ENTRY HAS BEEN SUCCESSFULLY ADDED");
        
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here:
        
        
        db.connectionclosing();
        viewwork obj= new viewwork(ar);
        
        obj.setVisible(true);
        obj.setSize(1440,900);
        
       
        
        
        
    }//GEN-LAST:event_jLabel43MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registration obj=new Registration();
                obj.setVisible(true);
                obj.pack();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c12;
    private javax.swing.JCheckBox c13;
    private javax.swing.JCheckBox c14;
    private javax.swing.JCheckBox c15;
    private javax.swing.JCheckBox c16;
    private javax.swing.JCheckBox c17;
    private javax.swing.JCheckBox c18;
    private javax.swing.JCheckBox c19;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel labell;
    private javax.swing.JCheckBox lc1;
    private javax.swing.JCheckBox lc2;
    private javax.swing.JPanel p1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
